// A generic word list (not Codenames' copyrighted list).
export const WORDS = [
  "AFRICA", "AGENT", "AIR", "ALIEN", "ALPS", "AMAZON", "ANCHOR", "ANGEL",
  "ANTARCTICA", "APPLE", "ARM", "ATLANTIS", "AZTEC", "BACK", "BALL", "BAND",
  "BANK", "BAR", "BARK", "BEACH", "BEAR", "BEAT", "BED", "BEIJING",
  "BELL", "BELT", "BERLIN", "BERMUDA", "BERRY", "BILL", "BLOCK", "BOARD",
  "BOLT", "BOMB", "BOND", "BOOM", "BOOT", "BOTTLE", "BOW", "BOX",
  "BRIDGE", "BRUSH", "BUCK", "BUFFALO", "BUG", "BUGLE", "BUTTON", "CALF",
  "CANADA", "CAP", "CAPITAL", "CAR", "CARD", "CARROT", "CASINO", "CAST",
  "CAT", "CELL", "CENTAUR", "CENTER", "CHAIR", "CHANGE", "CHARGE", "CHECK",
  "CHEST", "CHICK", "CHINA", "CHOCOLATE", "CHURCH", "CIRCLE", "CLIFF", "CLOAK",
  "CLUB", "CODE", "COLD", "COMIC", "COMPOUND", "CONCERT", "CONDUCTOR", "CONTRACT",
  "COOK", "COPPER", "COTTON", "COURT", "COVER", "CRANE", "CRASH", "CRICKET",
  "CROSS", "CROWN", "CYCLE", "CZECH", "DANCE", "DATE", "DAY", "DEATH",
  "DECK", "DEGREE", "DIAMOND", "DICE", "DINOSAUR", "DISEASE", "DOCTOR", "DOG",
  "DRAFT", "DRAGON", "DRESS", "DRILL", "DROP", "DUCK", "DWARF", "EAGLE",
  "EGYPT", "EMBASSY", "ENGINE", "ENGLAND", "EUROPE", "EYE", "FACE", "FAIR",
  "FALL", "FAN", "FENCE", "FIELD", "FIGHTER", "FIGURE", "FILE", "FILM",
  "FIRE", "FISH", "FLUTE", "FLY", "FOOT", "FORCE", "FOREST", "FORK",
  "FRANCE", "GAME", "GAS", "GENIUS", "GERMANY", "GHOST", "GIANT", "GLASS",
  "GLOVE", "GOLD", "GRACE", "GRASS", "GREECE", "GREEN", "GROUND", "HAM",
  "HAND", "HAWK", "HEAD", "HEART", "HELICOPTER", "HIMALAYAS", "HOLE", "HOLLYWOOD",
  "HONEY", "HOOD", "HOOK", "HORN", "HORSE", "HOSPITAL", "HOTEL", "ICE",
  "INDIA", "IRON", "IVORY", "JACK", "JAM", "JET", "JUPITER", "KANGAROO",
  "KETCHUP", "KEY", "KID", "KING", "KIWI", "KNIFE", "KNIGHT", "LAB",
  "LAP", "LASER", "LAWYER", "LEAD", "LEMON", "LEPRECHAUN", "LIFE", "LIGHT",
  "LIMOUSINE", "LINE", "LINK", "LION", "LITTER", "LOCH", "LOCK", "LOG",
  "LONDON", "LUCK", "MAIL", "MAMMOTH", "MAPLE", "MARBLE", "MARCH", "MASS",
  "MATCH", "MERCURY", "MEXICO", "MICROSCOPE", "MILLIONAIRE", "MINE", "MINT", "MISSILE",
  "MODEL", "MOLE", "MOON", "MOSCOW", "MOUNT", "MOUSE", "MOUTH", "MUG",
  "NAIL", "NEEDLE", "NET", "NEW YORK", "NIGHT", "NINJA", "NOTE", "NOVEL",
  "NURSE", "NUT", "OCTOPUS", "OIL", "OLIVE", "OLYMPUS", "OPERA", "ORANGE",
  "ORGAN", "PALM", "PAN", "PANTS", "PAPER", "PARACHUTE", "PARK", "PART",
  "PASS", "PASTE", "PENGUIN", "PHOENIX", "PIANO", "PIE", "PILOT", "PIN",
  "PIPE", "PIRATE", "PISTOL", "PIT", "PLANE", "PLASTIC", "PLATE", "PLATYPUS",
  "PLAY", "PLOT", "POINT", "POISON", "POLE", "POLICE", "POOL", "PORT",
  "POST", "POUND", "PRESS", "PRINCESS", "PUMPKIN", "PUPIL", "PYRAMID", "QUEEN",
  "RABBIT", "RACKET", "RAY", "REVOLUTION", "RING", "ROBIN", "ROBOT", "ROCK",
  "ROME", "ROOT", "ROSE", "ROULETTE", "ROUND", "ROW", "RULER", "SATELLITE",
  "SATURN", "SCALE", "SCHOOL", "SCIENTIST", "SCORPION", "SCREEN", "SCUBA DIVER", "SEAL",
  "SERVER", "SHADOW", "SHAKESPEARE", "SHARK", "SHIP", "SHOE", "SHOP", "SHOT",
  "SINK", "SKYSCRAPER", "SLIP", "SLUG", "SMUGGLER", "SNOW", "SNOWMAN", "SOCK",
  "SOLDIER", "SOUL", "SOUND", "SPACE", "SPELL", "SPIDER", "SPIKE", "SPINE",
  "SPOT", "SPRING", "SPY", "SQUARE", "STADIUM", "STAFF", "STAR", "STATE",
  "STICK", "STOCK", "STRAW", "STREAM", "STRIKE", "STRING", "SUB", "SUIT",
  "SUPERHERO", "SWING", "SWITCH", "TABLE", "TABLET", "TAG", "TAIL", "TAP",
  "TEACHER", "TELESCOPE", "TEMPLE", "THEATER", "THIEF", "THUMB", "TICK", "TIE",
  "TIME", "TOKYO", "TOOTH", "TORCH", "TOWER", "TRACK", "TRAIN", "TRIANGLE",
  "TRIP", "TRUNK", "TUBE", "TURKEY", "UNDERTAKER", "UNICORN", "VACUUM", "VAN",
  "VET", "WAKE", "WALL", "WAR", "WASHER", "WASHINGTON", "WATCH", "WATER",
  "WAVE", "WEB", "WELL", "WHALE", "WHIP", "WIND", "WITCH", "WORM", "YARD"
];

export const THEMES = {
  "Default": WORDS,
  "Animals": [
    "LION", "TIGER", "BEAR", "WOLF", "FOX", "DEER", "MOOSE", "RABBIT", "SQUIRREL",
    "BEAVER", "OTTER", "BADGER", "HEDGEHOG", "MOLE", "BAT", "OWL", "EAGLE", "HAWK",
    "FALCON", "ROBIN", "SPARROW", "CROW", "RAVEN", "PARROT", "PENGUIN", "OSTRICH",
    "FLAMINGO", "PEACOCK", "SWAN", "DUCK", "GOOSE", "CHICKEN", "TURKEY", "HORSE",
    "DONKEY", "ZEBRA", "GIRAFFE", "ELEPHANT", "RHINO", "HIPPO", "CAMEL", "KANGAROO",
    "KOALA", "PANDA", "MONKEY", "GORILLA", "SLOTH", "CROCODILE", "SNAKE", "LIZARD",
    "TURTLE", "FROG", "SHARK", "WHALE", "DOLPHIN", "OCTOPUS", "JELLYFISH", "CRAB",
    "LOBSTER", "STARFISH", "SEAHORSE", "SEAL", "WALRUS"
  ],
  "Movies & TV": [
    "ACTOR", "DIRECTOR", "SCRIPT", "SCENE", "CAMERA", "STUDIO", "SEQUEL", "TRAILER",
    "POPCORN", "OSCAR", "VILLAIN", "HERO", "SIDEKICK", "PLOT", "TWIST", "CLIFFHANGER",
    "PILOT", "EPISODE", "SEASON", "FINALE", "REBOOT", "REMAKE", "CARTOON", "ANIMATION",
    "COMEDY", "DRAMA", "THRILLER", "HORROR", "WESTERN", "MUSICAL", "ROMANCE",
    "DOCUMENTARY", "BLOCKBUSTER", "CASTING", "STUNT", "CAMEO", "MONTAGE", "SOUNDTRACK",
    "CREDITS", "PREMIERE", "RED CARPET", "SCREEN", "THEATER", "MATINEE", "BINGE",
    "STREAMING", "NETWORK", "CHANNEL", "SITCOM", "SPINOFF", "FRANCHISE", "PREQUEL",
    "SCREENPLAY", "BOX OFFICE"
  ],
  "Food & Drink": [
    "APPLE", "BANANA", "ORANGE", "GRAPE", "LEMON", "LIME", "CHERRY", "PEACH", "MANGO",
    "MELON", "BERRY", "BREAD", "BUTTER", "CHEESE", "EGG", "BACON", "SAUSAGE", "STEAK",
    "RICE", "PASTA", "NOODLE", "PIZZA", "BURGER", "TACO", "SUSHI", "SALAD", "SOUP",
    "STEW", "CURRY", "SAUCE", "PEPPER", "SALT", "SUGAR", "HONEY", "JAM", "CAKE",
    "COOKIE", "PIE", "DONUT", "CHOCOLATE", "CANDY", "ICE CREAM", "COFFEE", "TEA",
    "JUICE", "SODA", "MILK", "WINE", "SMOOTHIE", "PANCAKE", "WAFFLE", "CEREAL",
    "TOAST", "OMELETTE"
  ],
  "Space": [
    "STAR", "PLANET", "MOON", "SUN", "COMET", "ASTEROID", "METEOR", "GALAXY", "NEBULA",
    "COSMOS", "ORBIT", "GRAVITY", "ECLIPSE", "CRATER", "ROCKET", "SHUTTLE", "SATELLITE",
    "PROBE", "ROVER", "LANDER", "ASTRONAUT", "COSMONAUT", "SPACESUIT", "HELMET",
    "LAUNCH", "COUNTDOWN", "MISSION", "STATION", "TELESCOPE", "OBSERVATORY", "MERCURY",
    "VENUS", "EARTH", "MARS", "JUPITER", "SATURN", "URANUS", "NEPTUNE", "PLUTO",
    "BLACK HOLE", "SUPERNOVA", "CONSTELLATION", "ASTRONOMY", "UNIVERSE", "METEORITE",
    "SOLAR", "LUNAR", "ALIEN", "UFO"
  ],
  "Sports": [
    "SOCCER", "FOOTBALL", "BASEBALL", "BASKETBALL", "HOCKEY", "TENNIS", "GOLF",
    "CRICKET", "RUGBY", "VOLLEYBALL", "BADMINTON", "BOXING", "WRESTLING", "JUDO",
    "KARATE", "FENCING", "ARCHERY", "ROWING", "SAILING", "SURFING", "SKIING",
    "SNOWBOARD", "SKATING", "CYCLING", "RUNNING", "SPRINT", "MARATHON", "HURDLES",
    "JAVELIN", "DISCUS", "GYMNASTICS", "DIVING", "SWIMMING", "BOWLING", "BILLIARDS",
    "DARTS", "CURLING", "LACROSSE", "POLO", "REFEREE", "UMPIRE", "COACH", "STADIUM",
    "JERSEY", "TROPHY", "MEDAL", "WHISTLE", "PENALTY", "OFFSIDE", "TOUCHDOWN", "DUNK",
    "SERVE", "RALLY"
  ],
};

export function parseWordList(text) {
  const seen = new Set();
  const out = [];
  for (const raw of String(text).split(/[\n,]+/)) {
    const w = raw.trim().toUpperCase();
    if (w && !seen.has(w)) {
      seen.add(w);
      out.push(w);
    }
  }
  return out;
}
